% This code provides a demo for code of following paper: 
% An Illumination-Robust Approach for Feature-Based Road Detection
% (Zhenqiang Ying, Ge Li, Guozhen Tan) in 
% 2015 IEEE International Symposium on Multimedia (ISM).
%
% Email: yinzhenqiang # gmail.com
% Website: https://github.com/baidut/openvehiclevision

function demo(method, roma_path)

if nargin < 2
    roma_path = './roma';
    if nargin < 1 || isempty(method)
        method = 'ours';  % 'y', 'h','s', 'ours'
    end
end

folder = ['results-' method];
mkdir(folder);

global db; % debugger

db = exDebugger(...
    'saveAsEps',true,... % output .eps file for evaluation report
    'nameFunc',@(x)get(x,'Name'),...  %@(x)x.Name,... not work in Matlab R2014a
    'level',1,...
    'path',folder...
);

roma = RomaDataset(roma_path);

files = roma.data.filename;

N = numel(files);
missL = false(N,1);
missM = false(N,1);
missR = false(N,1);
falseL = false(N,1);
falseM = false(N,1);
falseR = false(N,1);

for n = 1 : N
    fprintf('Processing:%s...\n',files{n});
	[fig, missL(n), missM(n), missR(n)]  = roadDetection(files{n}, method);
    db.imdumpd(1, fig); 
    close(fig);
end

%% table
name = roma.data.name;
situation = roma.data.situation;
scenario = roma.data.scenario;

t = table(name, missL, missM, missR, falseL, falseM, falseR, ...
    situation, scenario);
writetable(t, ['eval-' method '.csv'],'Delimiter',',','QuoteStrings',true);
 
%% generate evaluation report (.tex)
text = evalc(['gentex ' roma_path]);
file = fullfile(folder,'evaluation.tex');
fid = fopen(file,'w');
fprintf(fid, '%s', text);
fclose(fid);

end

%% generate evaluation report (.tex)
function gentex(roma_path)

path = roma_path;
title = 'Supplementary Material for Paper \\ An Illumination-Robust Approach for Feature-Based Road Detection';
author = 'Zhenqiang Ying, Ge Li and Guozhen Tan';

%% gen '.tex' file automatically
disp('%%This tex file is generated by matlab code automatically, see "gentex.m"');
disp('\documentclass[landscape,8pt]{article}'); % twocolumn,a4paper
disp('\usepackage[pdftex]{graphicx}');
disp('\DeclareGraphicsExtensions{.eps}');
disp('\usepackage{subfigure}'); %[tight,footnotesize]
disp('\renewcommand{\thesubfigure}{\thefigure.\arabic{subfigure}}');
disp('\usepackage{geometry}');
disp('\geometry{left=0.5cm,right=0.5cm,top=2cm,bottom=2cm}');
disp(char(10));

disp('\begin{document}');
fprintf('\\title{%s}\n',title);
fprintf('\\author{%s}\n',author);
disp('\maketitle');
disp(char(10));


dataset = 'roma';
situation = subfolder(path);
imagelist = {'img.mov', 'imgnormal.mov', 'imgadvlight.mov', 'imghighcurv.mov'};
scenarios = {'Normal', 'Adverse Light', 'Curved Road'};

addpath(path); % call loadlist

% disp(['\section{',dataset,'}']);
disp(['\section{Overall}']);
n = 1; % 'img.mov' - the list of all the original images
for m = 1:length(situation)
    movFile = fullfile(path,situation{m},imagelist{n});
    files = loadlist(movFile);
    disp('\begin{figure}[!h]\centering'); % 
    for i = 1:length(files)
        [~, name, ~] = fileparts(files{i});
        disp(['\subfigure[' name ']{' ... 
                         '\includegraphics[width=0.5in]{' name '}' ...
            '}']);% \label{fig:' ,dataset,situation{m},name, '}
        %if mod(i,3)==0, disp('\\'); end
    end
    disp(['\caption{', ...
        sprintf('%s/%s/%s',dataset,situation{m},imagelist{n}), ...
        '}']);
    disp(['\end{figure}' 10]);
end

disp('\clearpage ');
% disp('\cleardoublepage');

disp(['\section{Scenarios}']); % Challenging
for n = 2:length(imagelist)
    disp(['\subsection{',scenarios{n-1},'}']);
    disp('\begin{figure}[!h]\centering'); % \centering
    
    for m = 1:length(situation)
		movFile = fullfile(path,situation{m},imagelist{n});
		files = loadlist(movFile);
		for i = 1:length(files)
			[~, name, ~] = fileparts(files{i});
			disp(['\subfigure[' name ']{' ... 
				             '\includegraphics[width=0.5in]{' name '}' ...
				'}']);% \label{fig:' ,dataset,situation{m},name, '}
			%if mod(i,3)==0, disp('\\'); end
		end
    end
    disp(['\caption{', ...
			sprintf('%s/%s/%s',dataset,situation{m},imagelist{n}), ...
			'}']);
    disp(['\end{figure}' 10]);
    %if mod(i,2)==0, disp('\clearpage'); end
end

disp('\end{document}');

end